### ISSUE TITLE
如何安装呀

### ISSUE THREAD

**Issue by junyiiu** [seth-shi/monday-shop#17]
各位大哥们，这个源代码上传宝塔后该怎么安装呀，搞不明白。

**Comment by alsj668** [comment]
https://github.com/seth-shi/monday-shop#installation

**Comment by alsj668** [comment]
不看文档的吗?

**Comment by junyiiu** [comment]
> 不看文档的吗?

文档我看了 我说的是在宝塔面板里面需要怎么安装，文档里面没有写 我也不懂 所以来问了一下
