### ISSUE TITLE
php artisan moon:install 出现 elasticsearch 400 错误

### ISSUE THREAD

**Issue by Leyls** [seth-shi/monday-shop#20]
错误名称： mapping parse execution 错误
_doc 和 ik_smart 没有 mapping

系统 openSUSE Leap 15.2
redis 最新的stable版本 6.2.4
mysql 5.7.15
elasticsearch 最新版本

**Comment by Oferiston** [comment]
详细错误： elasticseach/Elasticsearch

In Connection.php line 632:

  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to pa  
  rse mapping [_doc]: analyzer [ik_smart] has not been configured in mappings"}],"t  
  ype":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyze  
  r [ik_smart] has not been configured in mappings","caused_by":{"type":"illegal_ar  
  gument_exception","reason":"analyzer [ik_smart] has not been configured in mappin  
  gs"}},"status":400}

**Comment by Leyls** [comment]
問題已經解決，只需要安裝你 elasticsearch 對應版本的 analysis_ik 就可以解決。
安裝方式鏈接如下：
https://github.com/medcl/elasticsearch-analysis-ik
我使用的是 elasticsearch-plugin install，注意替換鏈接中的爲自身 elasticsearch 版本
