### ISSUE TITLE
ipaddress/server.php 跳轉後沒有相關文件

### ISSUE THREAD

**Issue by Leyls** [seth-shi/monday-shop#21]
目前訪問 IPAddress/server.php 能夠顯示頁面，但是缺少排版，同時無法跳轉，例如點擊商品無法跳轉至 IPAddress/products, 目標文件夾應該是 public, 但是在此文件夾並未找到相關文件，另外，也沒有找到 resources/templates 文件夾。

**Comment by seth-shi** [comment]
请参考 laravel 把 web 目录指向 IPAddress/public/, 访问的应是 IPAddress/public/index.php
