### ISSUE TITLE
构建docker镜像时报错

### ISSUE THREAD

**Issue by puyuanzhang** [seth-shi/monday-shop#37]
系统平台为Ubuntu Docker版本20.10.12
报错信息如下
`Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-cors
Discovered Package: fideloper/proxy
Discovered Package: hhxsv5/laravel-s
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: tymon/jwt-auth
Package manifest generated successfully.
55 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
  ation_schema.tables where table_schema = shop and table_name = migrations a  
  nd table_type = 'BASE TABLE')                                                
                                                                               

In Exception.php line 18:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 40:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

The command '/bin/sh -c chmod -R 0777 storage &&     chmod -R 0777 bootstrap/cache &&     composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ &&     composer install --optimize-autoloader --no-dev &&     php artisan config:cache &&     php artisan route:cache &&     php artisan migrate &&     php artisan storage:link &&     php artisan moon:copy' returned a non-zero code: 1`
请作者大大赐教

**Comment by seth-shi** [comment]
最新版本已修复好
https://github.com/seth-shi/monday-shop/commit/6335df4b4c58afe13f975878ad5e5f63e3d01ff1
